services:
  sql-server-db:
    container_name: sql-server-db
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "1433:1433"
    volumes:
      - ./.docker/data:/var/opt/mssql/data
      - ./.docker/log:/var/opt/mssql/log
      - ./.docker/secrets:/var/opt/mssql/secrets
    environment:
      MSSQL_SA_PASSWORD: "123RootSqlServer"
      ACCEPT_EULA: "Y"
